# Generated by Django 6.0.1 on 2026-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
