# Generated by Django 6.0.1 on 2026-02-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentmethod_instruction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentInstruction',
        ),
    ]
