# Generated by Django 6.0.1 on 2026-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_paymentinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaymentrequest',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpaymentrequest',
            name='wallet_credited',
            field=models.BooleanField(default=False),
        ),
    ]
