# Generated by Django 6.0.1 on 2026-02-24 08:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profitdistribution_and_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitdistribution',
            name='total_referral_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='total_won_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='profitdistributionentry',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='profitdistributionentry',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distribution_entries', to='core.investment'),
        ),
        migrations.AddField(
            model_name='profitdistributionentry',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='profitdistributionentry',
            name='won_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
