# Generated by Django 6.0.1 on 2026-02-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_unsettled_balance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionlog',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_logs', to='core.profitdistribution'),
        ),
    ]
