# Generated by Django 6.0.1 on 2026-02-24 19:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_withdrawalmethod_manualwithdrawalrequest_net_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualwithdrawalrequest',
            name='withdrawal_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='withdrawalmethod',
            name='withdrawal_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
