# Generated by Django 6.0.1 on 2026-04-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_emailconfiguration_notification_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('NID', 'NID'), ('DRIVING_LICENCE', 'Driving Licence')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='UserNominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('identity_type', models.CharField(blank=True, choices=[('NID', 'NID'), ('DRIVING_LICENCE', 'Driving Licence')], default='', max_length=20)),
                ('identity_number', models.CharField(blank=True, default='', max_length=64)),
                ('identity_image', models.ImageField(blank=True, null=True, upload_to='identity_documents/nominees/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
