# Generated by Django 6.0.1 on 2026-04-03 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='last_topped_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='matured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('NID', 'NID'), ('DRIVING_LICENCE', 'Driving Licence'), ('PASSPORT', 'Passport')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernominee',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('NID', 'NID'), ('DRIVING_LICENCE', 'Driving Licence'), ('PASSPORT', 'Passport')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='InvestmentReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_return_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='core.investment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('previous_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('previous_ends_at', models.DateTimeField(blank=True, null=True)),
                ('new_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='core.investment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
