# Generated by GPT for schema self-heal (SQLite/MySQL safe)

from django.db import migrations


def ensure_systemconfiguration_columns(apps, schema_editor):
    SystemConfiguration = apps.get_model("core", "SystemConfiguration")
    table = SystemConfiguration._meta.db_table

    existing_columns = set()
    for col in schema_editor.connection.introspection.get_table_description(
        schema_editor.connection.cursor(), table
    ):
        existing_columns.add(col.name)

    for field_name in ("min_investment_amount", "min_withdrawal_amount"):
        if field_name in existing_columns:
            continue
        field = SystemConfiguration._meta.get_field(field_name)
        schema_editor.add_field(SystemConfiguration, field)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_investment_last_topped_up_at_investment_matured_at_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_systemconfiguration_columns, migrations.RunPython.noop),
    ]

