# Generated by Django 6.0.1 on 2026-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_systemconfiguration_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='admin_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated admin email addresses to receive master notifications.'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='notify_admin_events_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
