# Generated by Django 6.0.1 on 2026-04-04 15:53

from collections import defaultdict

from django.db import migrations, models


def dedupe_user_emails(apps, schema_editor):
    """
    Ensure emails are unique (case-insensitive) before adding the DB constraint.

    For any duplicate email group, keep the lowest-id user as canonical and
    rewrite the others to a guaranteed-unique placeholder email.
    """
    User = apps.get_model("core", "User")
    rows = (
        User.objects.exclude(email__isnull=True)
        .exclude(email="")
        .values_list("id", "email")
        .order_by("id")
    )

    groups = defaultdict(list)
    for user_id, email in rows:
        key = (email or "").strip().lower()
        if key:
            groups[key].append((user_id, email))

    for key, items in groups.items():
        if len(items) <= 1:
            continue
        canonical_id = items[0][0]
        User.objects.filter(id=canonical_id).update(email=key)
        duplicate_ids = [user_id for user_id, _ in items[1:]]
        for user_id in duplicate_ids:
            User.objects.filter(id=user_id).update(
                email=f"duplicate-{user_id}@invalid.local",
                email_verified=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0035_emailconfiguration_admin_notification_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(dedupe_user_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), condition=models.Q(('email', ''), _negated=True), name='uniq_core_user_email_nonempty'),
        ),
    ]
